name: lobe-yolov5-py36
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy
  - pillow
  - pyqt=5
  - pyserial
  - opencv
  - pip:
    - torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - torchvision==0.8.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - opencv-python
